[package]
name = "qr_reader_pc"
version = "0.3.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
qr_reader_phone = {path = "../qr_reader_phone"}
anyhow = "1.0.42"

[dependencies.opencv]
version = "0.61"
default-features = false
features = ["clang-runtime", "videoio", "imgproc", "highgui", "objdetect", "imgcodecs"]
