[package]
name = "qr_reader_pc"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
#nokhwa = {version = "0.8.0", features = ["input-v4l"]}
opencv = { version = "0.58", features = ["clang-runtime"]}
image = "0.23.14"
raptorq = "1.6.4"
qr_reader_phone = {path = "../qr_reader_phone"}
#quircs = "0.10.0"
anyhow = "1.0.42"
#minifb = "0.19.3"
