[package]
name = "qr_reader_pc"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
opencv = { version = "0.58", features = ["clang-runtime"]}
qr_reader_phone = {path = "../qr_reader_phone"}
anyhow = "1.0.42"

